"""Recommended pair data — loaded from matrix bench data (Phase 5-D follow-up).

Source of truth: ``recommended_pairs.json`` next to this module, generated by
``scripts/gen_recommended_pairs.py`` from 208-cell matrix bench retro judge.

Why JSON-on-disk instead of hard-coded Python:
* Data churn risk — re-running matrix bench produces a new file
* Generator script already builds the structure; we just consume it
* JSON file is checked in so the API can serve even without re-running gen

Why lazy load:
* Avoid import-time disk IO when only THEME_SEEDS / STYLE_PRESETS are needed
* File missing falls back to empty dict — API still returns
  ``recommended_available: False`` cleanly
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_DATA_PATH = Path(__file__).resolve().parent / "recommended_pairs.json"


@lru_cache(maxsize=1)
def _load_data() -> dict[str, Any]:
    """Load the JSON once per process. Empty dict on any IO/parse error."""
    if not _DATA_PATH.is_file():
        logger.info("recommended_pairs.json missing at %s", _DATA_PATH)
        return {}
    try:
        return json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        logger.warning("Failed to load recommended_pairs.json: %s", e)
        return {}


def is_available() -> bool:
    """True when JSON file exists and parsed cleanly."""
    return bool(_load_data())


def top_styles_for_theme(theme_key: str, *, n: int = 3) -> list[dict[str, Any]]:
    """Return top-N style recommendations for a theme (rank 1..N).

    Each entry: ``{"style", "mean", "coh", "voice", "plot", "rank", "is_top"}``.
    Returns empty list if theme not scored or data unavailable.
    """
    data = _load_data()
    by_theme = data.get("by_theme") or {}
    rows = by_theme.get(theme_key) or []
    return [dict(r) for r in rows[: max(1, int(n))]]


def perfect_pairs() -> list[dict[str, Any]]:
    """Pairs with mean = 5.0 across all bench cells."""
    return list((_load_data().get("perfect_pairs") or []))


def avoid_pairs() -> list[dict[str, Any]]:
    """Pairs with mean < 4.0 — UI should warn or hide."""
    return list((_load_data().get("avoid_pairs") or []))


def style_universal_avg() -> dict[str, float]:
    """Per-style mean across all themes — for "safe choices" sorting."""
    raw = _load_data().get("style_universal_avg") or {}
    return {k: float(v) for k, v in raw.items()}


def to_api_payload() -> dict[str, Any]:
    """Compact dict for ``/api/presets`` response, keyed for UI consumption.

    Schema:
        {
            "available": bool,
            "version": 1,
            "by_theme": {
                "<theme_key>": [
                    {"style": "<key>", "mean": 4.67, "rank": 1, "is_top": true}
                ]
            },
            "perfect_pairs": [...],
            "avoid_pairs": [...],
            "style_universal_avg": {"<style_key>": 4.50}
        }

    Notes:
    * ``by_theme[*][i]`` is already rank-sorted by gen_recommended_pairs.
    * Only ``style/mean/rank/is_top`` are passed through — keeps the wire
      payload light; full dimension breakdown stays in the on-disk JSON.
    """
    data = _load_data()
    if not data:
        return {"available": False, "version": 0}
    return {
        "available": True,
        "version": int(data.get("version", 1)),
        "by_theme": {
            tk: [
                {
                    "style": r["style"],
                    "mean": r["mean"],
                    "rank": r["rank"],
                    "is_top": r["is_top"],
                }
                for r in rows
            ]
            for tk, rows in (data.get("by_theme") or {}).items()
        },
        "perfect_pairs": data.get("perfect_pairs") or [],
        "avoid_pairs": data.get("avoid_pairs") or [],
        "style_universal_avg": {
            k: float(v) for k, v in (data.get("style_universal_avg") or {}).items()
        },
    }
